#!/usr/bin/env php
<?php

foreach ([
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/../autoload.php',
    __DIR__ . '/../../vendor/autoload.php',
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/vendor/autoload.php'
 ] as $file) {
    if (file_exists($file)) {
        define('PHPUNIT_COMPOSER_INSTALL', $file);
        break;
    }
}

if (!defined('PHPUNIT_COMPOSER_INSTALL')) {
    fwrite(
        STDERR,
        'You need to set up the project dependencies using Composer:' . PHP_EOL . PHP_EOL .
        '    composer install' . PHP_EOL . PHP_EOL .
        'You can learn all about Composer on https://getcomposer.org/.' . PHP_EOL
    );
    die(1);
}

require PHPUNIT_COMPOSER_INSTALL;

use Illuminate\Database\Schema\Blueprint;

define('ROOT_FOLDER', __DIR__ . '/../../');
\Kanata\Services\Bootstrap::processCore(['skip_plugins' => true]);

// -----------------------------------------------------
// prepare json dbs
// -----------------------------------------------------

// plugins
if (!mysql_table_exists(DB_DATABASE, \Kanata\Models\Plugin::TABLE_NAME)) {
    dd(mysql_table_exists(DB_DATABASE, \Kanata\Models\Plugin::TABLE_NAME));
    container()->db->schema()->create(\Kanata\Models\Plugin::TABLE_NAME, function (Blueprint $table) {
        $table->increments('id');
        $table->boolean('active');
        $table->string('directory_name');
        $table->string('path');
        $table->string('name');
        $table->string('author_name')->nullable();
        $table->string('author_email')->nullable();
        $table->string('description')->nullable();
        $table->timestamps();
    });
}

// ws channels
if (!mysql_table_exists(DB_DATABASE, \Kanata\Models\WsChannel::TABLE_NAME)) {
    container()->db->schema()->create(\Kanata\Models\WsChannel::TABLE_NAME, function (Blueprint $table) {
        $table->increments('id');
        $table->integer('fd');
        $table->string('channel');
        $table->timestamps();
    });
}

// ws listeners
if (!mysql_table_exists(DB_DATABASE, \Kanata\Models\WsListener::TABLE_NAME)) {
    container()->db->schema()->create(\Kanata\Models\WsListener::TABLE_NAME, function (Blueprint $table) {
        $table->increments('id');
        $table->integer('fd');
        $table->string('action');
        $table->timestamps();
    });
}

// ws communications
if (!mysql_table_exists(DB_DATABASE, \Kanata\Models\WsCommunication::TABLE_NAME)) {
    container()->db->schema()->create(\Kanata\Models\WsCommunication::TABLE_NAME, function (Blueprint $table) {
        $table->increments('id');
        $table->string('action');
        $table->string('data');
        $table->timestamps();
    });
}

// ws associations
if (!mysql_table_exists(DB_DATABASE, \Kanata\Models\WsAssociation::TABLE_NAME)) {
    container()->db->schema()->create(\Kanata\Models\WsAssociation::TABLE_NAME, function (Blueprint $table) {
        $table->increments('id');
        $table->integer('fd');
        $table->integer('user_id');
        $table->timestamps();
    });
}
